import React, { createContext, useContext, useState, ReactNode } from "react";

export type LanguageCode = "en" | "hi" | "mr" | "gu" | "ta" | "te" | "kn" | "ml" | "pa" | "ur" | "bn";

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appTitle: "Smart Bharat AI",
    appSubtitle: "India's Intelligent Digital Civic Companion",
    oneNation: "One Nation. One AI Companion.",
    getStarted: "Get Started",
    talkToAi: "Talk to AI",
    watchDemo: "Watch Demo",
    navHome: "Home",
    navChat: "AI Assistant",
    navServices: "Services",
    navComplaints: "Civic Complaints",
    navSchemes: "Schemes",
    navResources: "Resources",
    navDashboard: "Dashboard",
    navProfile: "My Profile",
    heroHeading: "Your Intelligent AI Companion for Government Services",
    heroSubheading: "Access government services, report civic issues, verify documents, discover schemes, and receive AI assistance in multiple Indian languages instantly.",
    securePortal: "SECURE GOVERNMENT PORTAL",
    verifiedBadge: "Government of India Approved",
    login: "Log In",
    signup: "Sign Up",
    logout: "Log Out",
    welcomeBack: "Welcome to Smart Bharat AI",
    chooseRole: "Choose how you want to continue",
    guestMode: "Continue as Guest",
    verifyDoc: "Verify Documents",
    summarizePdf: "Summarize Policy PDF",
    reportIssue: "Report Issue",
    searchPlaceholder: "Ask me anything about Indian government services...",
    aadhaarBadge: "DigiLocker Verified"
  },
  hi: {
    appTitle: "स्मार्ट भारत एआई",
    appSubtitle: "भारत का बुद्धिमान डिजिटल नागरिक साथी",
    oneNation: "एक राष्ट्र। एक एआई साथी।",
    getStarted: "शुरू करें",
    talkToAi: "एआई से बात करें",
    watchDemo: "डेमो देखें",
    navHome: "मुख्य पृष्ठ",
    navChat: "एआई सहायक",
    navServices: "सरकारी सेवाएं",
    navComplaints: "नागरिक शिकायतें",
    navSchemes: "योजनाएं",
    navResources: "संसाधन",
    navDashboard: "डैशबोर्ड",
    navProfile: "मेरी प्रोफ़ाइल",
    heroHeading: "सरकारी सेवाओं के लिए आपका बुद्धिमान एआई साथी",
    heroSubheading: "सरकारी सेवाओं तक पहुंचें, नागरिक मुद्दों की रिपोर्ट करें, दस्तावेजों को सत्यापित करें, योजनाओं की खोज करें और तुरंत कई भारतीय भाषाओं में एआई सहायता प्राप्त करें।",
    securePortal: "सुरक्षित सरकारी पोर्टल",
    verifiedBadge: "भारत सरकार द्वारा अनुमोदित",
    login: "लॉग इन करें",
    signup: "साइन अप करें",
    logout: "लॉग आउट",
    welcomeBack: "स्मार्ट भारत एआई में आपका स्वागत है",
    chooseRole: "चुनें कि आप कैसे जारी रखना चाहते हैं",
    guestMode: "अतिथि के रूप में जारी रखें",
    verifyDoc: "दस्तावेज़ सत्यापित करें",
    summarizePdf: "नीति पीडीएफ सारांश",
    reportIssue: "मुद्दे की रिपोर्ट करें",
    searchPlaceholder: "भारतीय सरकारी सेवाओं के बारे में मुझसे कुछ भी पूछें...",
    aadhaarBadge: "डिजी लॉकर सत्यापित"
  },
  mr: {
    appTitle: "स्मार्ट भारत एआय",
    appSubtitle: "भारताचा बुद्धिमान डिजिटल नागरी सहकारी",
    oneNation: "एक देश. एक एआय सहकारी.",
    getStarted: "सुरू करा",
    talkToAi: "एआय शी बोला",
    watchDemo: "डेमो पहा",
    navHome: "मुख्यपृष्ठ",
    navChat: "एआय सहाय्यक",
    navServices: "सरकारी सेवा",
    navComplaints: "नागरी तक्रारी",
    navSchemes: "योजना",
    navResources: "संसाधन",
    navDashboard: "डॅशबोर्ड",
    navProfile: "माझी प्रोफाइल",
    heroHeading: "सरकारी सेवांसाठी आपला बुद्धिमान एआय सहकारी",
    heroSubheading: "सरकारी सेवांमध्ये प्रवेश करा, नागरी समस्यांची तक्रार करा, दस्तऐवज पडताळणी करा, योजना शोधा आणि एकाच वेळी अनेक भारतीय भाषांमध्ये एआय मदत मिळवा.",
    securePortal: "सुरक्षित सरकारी पोर्टल",
    verifiedBadge: "भारत सरकार मान्यताप्राप्त",
    login: "लॉग इन करा",
    signup: "साइन अप करा",
    logout: "लॉग आउट",
    welcomeBack: "स्मार्ट भारत एआय मध्ये आपले स्वागत आहे",
    chooseRole: "तुम्हाला कसे पुढे जायचे आहे ते निवडा",
    guestMode: "अतिथी म्हणून पुढे जा",
    verifyDoc: "दस्तऐवज पडताळा",
    summarizePdf: "धोरण पीडीएफ सारांश",
    reportIssue: "समस्या नोंदवा",
    searchPlaceholder: "भारतीय सरकारी सेवांबद्दल मला काहीही विचारा...",
    aadhaarBadge: "डिजी लॉकर पडताळणी"
  },
  gu: {
    appTitle: "સ્માર્ટ ભારત AI",
    appSubtitle: "ભારતનું બુદ્ધિશાળી ડિજિટલ નાગરિક સાથી",
    oneNation: "એક રાષ્ટ્ર. એક AI સાથી.",
    getStarted: "શરૂ કરો",
    talkToAi: "AI સાથે વાત કરો",
    watchDemo: "ડેમો જુઓ",
    navHome: "મુખ્ય પૃષ્ઠ",
    navChat: "AI સહાયક",
    navServices: "સરકારી સેવાઓ",
    navComplaints: "નાગરિક ફરિયાદો",
    navSchemes: "યોજનાઓ",
    navResources: "સંસાધનો",
    navDashboard: "ડેશબોર્ડ",
    navProfile: "મારી પ્રોફાઇલ",
    heroHeading: "સરકારી સેવાઓ માટે તમારો બુદ્ધિશાળी AI સાથી",
    heroSubheading: "સરકારી સેવાઓ મેળવો, નાગરિક સમસ્યાઓની જાણ કરો, દસ્તાવેજો ચકાસો, યોજનાઓ શોધો અને બહુવિધ ભારતીય ભાષાઓમાં ત્વરિત AI સહાય મેળવો.",
    securePortal: "સુરક્ષિત સરકારી પોર્ટલ",
    verifiedBadge: "ભારત સરકાર માન્ય",
    login: "લોગ ઇન",
    signup: "સાઇન અપ",
    logout: "લોગ આઉટ",
    welcomeBack: "સ્માર્ટ ભારત AI માં તમારું સ્વાગત છે",
    chooseRole: "તમે કેવી રીતે આગળ વધવા માંગો છો તે પસંદ કરો",
    guestMode: "અતિથિ તરીકે ચાલુ રાખો",
    verifyDoc: "દસ્તાવેજ ચકાસો",
    summarizePdf: "નીતિ પીડીએફ સારાંશ",
    reportIssue: "સમસ્યાની જાણ કરો",
    searchPlaceholder: "સરકારી સેવાઓ વિશે મને કંઈપણ પૂછો...",
    aadhaarBadge: "ડીજીલોકર વેરિફાઇડ"
  },
  ta: {
    appTitle: "ஸ்மார்ட் பாரத் AI",
    appSubtitle: "இந்தியாவின் அறிவார்ந்த டிஜிட்டல் குடிமைத் துணைவன்",
    oneNation: "ஒரு தேசம். ஒரு AI துணை.",
    getStarted: "தொடங்குங்கள்",
    talkToAi: "AI உடன் பேசுங்கள்",
    watchDemo: "டெமோ பார்",
    navHome: "முகப்பு",
    navChat: "AI உதவியாளர்",
    navServices: "அரசு சேவைகள்",
    navComplaints: "புகார்கள்",
    navSchemes: "திட்டங்கள்",
    navResources: "வளங்கள்",
    navDashboard: "டாஷ்போர்டு",
    navProfile: "எனது சுயவிவரம்",
    heroHeading: "அரசு சேவைகளுக்கான உங்கள் அறிவார்ந்த AI துணை",
    heroSubheading: "அரசு சேவைகளை அணுகவும், குடிமைப் பிரச்சினைகளைப் புகாரளிக்கவும், ஆவணங்களைச் சரிபார்க்கவும், திட்டங்களைக் கண்டறியவும், பல இந்திய மொழிகளில் உடனடியாக AI உதவியைப் பெறவும்.",
    securePortal: "பாதுகாப்பான அரசு போர்ட்டல்",
    verifiedBadge: "இந்திய அரசு அங்கீகரித்தது",
    login: "உள்நுழை",
    signup: "பதிவு செய்",
    logout: "வெளியேறு",
    welcomeBack: "ஸ்மார்ட் பாரத் AI க்கு உங்களை வரவேற்கிறோம்",
    chooseRole: "எப்படி தொடர விரும்புகிறீர்கள் என்பதைத் தேர்வுசெய்க",
    guestMode: "விருந்தினராகத் தொடரவும்",
    verifyDoc: "ஆவணங்களைச் சரிபார்",
    summarizePdf: "கொள்கை PDF சுருக்கம்",
    reportIssue: "பிரச்சினையைப் புகார் செய்",
    searchPlaceholder: "இந்திய அரசு சேவைகளைப் பற்றி என்னிடம் கேளுங்கள்...",
    aadhaarBadge: "டிஜிலாக்கர் சரிபார்க்கப்பட்டது"
  },
  te: {
    appTitle: "స్మార్ట్ భారత్ AI",
    appSubtitle: "భారతదేశపు ఇంటెలిజెంట్ డిజిటల్ సివిక్ కంపానియన్",
    oneNation: "ఒక దేశం. ఒక AI తోడు.",
    getStarted: "ప్రారంభించండి",
    talkToAi: "AI తో మాట్లాడండి",
    watchDemo: "డెమో చూడండి",
    navHome: "హోమ్",
    navChat: "AI సహాయకుడు",
    navServices: "ప్రభుత్వ సేవలు",
    navComplaints: "పౌర ఫిర్యాదులు",
    navSchemes: "పథకాలు",
    navResources: "వనరులు",
    navDashboard: "డాష్‌బోర్డ్",
    navProfile: "నా ప్రొఫైల్",
    heroHeading: "ప్రభుత్వ సేవల కోసం మీ ఇంటెలిజెంట్ AI తోడు",
    heroSubheading: "ప్రభుత్వ సేవలను యాక్సెస్ చేయండి, పౌర సమస్యలను నివేదించండి, పత్రాలను ధృవీకరించండి, పథకాలను కనుగొనండి మరియు బహుళ భారతీయ భాషలలో తక్షణమే AI సహాయాన్ని పొందండి.",
    securePortal: "సురక్షిత ప్రభుత్వ పోర్టల్",
    verifiedBadge: "భారత ప్రభుత్వం ఆమోదించింది",
    login: "లాగిన్ అవ్వండి",
    signup: "సైన్ అప్ చేయండి",
    logout: "లాగ్ అవుట్",
    welcomeBack: "స్మార్ట్ భారత్ AI కి స్వాగతం",
    chooseRole: "మీరు ఎలా కొనసాగాలనుకుంటున్నారో ఎంచుకోండి",
    guestMode: "గెస్ట్‌గా కొనసాగండి",
    verifyDoc: "పత్రాల ధృవీకరణ",
    summarizePdf: "విధానాల పిడిఎఫ్ సారాంశం",
    reportIssue: "సమస్యను నివేదించండి",
    searchPlaceholder: "భారత ప్రభుత్వ సేవల గురించి నన్ను ఏదైనా అడగండి...",
    aadhaarBadge: "డిజిలాకర్ ధృవీకరించబడింది"
  },
  kn: {
    appTitle: "ಸ್ಮಾರ್ಟ್ ಭಾರತ್ AI",
    appSubtitle: "ಭಾರತದ ಬುದ್ಧಿವಂತ ಡಿಜಿಟಲ್ ನಾಗರಿಕ ಒಡನಾಡಿ",
    oneNation: "ಒಂದು ರಾಷ್ಟ್ರ. ಒಂದು AI ಒಡನಾಡಿ.",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    talkToAi: "AI ಯೊಂದಿಗೆ ಮಾತನಾಡಿ",
    watchDemo: "ಡೆಮೊ ವೀಕ್ಷಿಸಿ",
    navHome: "ಮುಖಪುಟ",
    navChat: "AI ಸಹಾಯಕ",
    navServices: "ಸರ್ಕಾರಿ ಸೇವೆಗಳು",
    navComplaints: "ನಾಗರಿಕ ದೂರುಗಳು",
    navSchemes: "ಯೋಜನೆಗಳು",
    navResources: "ಸಂಪನ್ಮೂಲಗಳು",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    heroHeading: "ಸರ್ಕಾರಿ ಸೇವೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ಬುದ್ಧಿವಂತ AI ಒಡನಾಡಿ",
    heroSubheading: "ಸರ್ಕಾರಿ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ, ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ, ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ ಮತ್ತು ಬಹು ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ತಕ್ಷಣ AI ಸಹಾಯವನ್ನು ಪಡೆಯಿರಿ.",
    securePortal: "ಸುರಕ್ಷಿತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್",
    verifiedBadge: "ಭಾರತ ಸರ್ಕಾರದಿಂದ ಅನುಮೋದಿಸಲಾಗಿದೆ",
    login: "ಲಾಗಿನ್ ಆಗಿ",
    signup: "ನೋಂದಾಯಿಸಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    welcomeBack: "ಸ್ಮಾರ್ಟ್ ಭಾರತ್ AI ಗೆ ಸುಸ್ವಾಗತ",
    chooseRole: "ನೀವು ಹೇಗೆ ಮುಂದುವರಿಯಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    guestMode: "ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ",
    verifyDoc: "ದಾಖಲೆ ಪರಿಶೀಲಿಸಿ",
    summarizePdf: "ನೀತಿ ಪಿಡಿಎಫ್ ಸಾರಾಂಶ",
    reportIssue: "ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    searchPlaceholder: "ಸರ್ಕಾರಿ ಸೇವೆಗಳ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ...",
    aadhaarBadge: "ಡಿಜಿಲಾಕರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ"
  },
  ml: {
    appTitle: "സ്മാർട്ട് ഭാരത് AI",
    appSubtitle: "ഭാരതത്തിന്റെ ബുദ്ധിമാനായ ഡിജിറ്റൽ സിവിക് സഹചാരി",
    oneNation: "ഒരു രാജ്യം. ഒരു AI സഹചാരി.",
    getStarted: "ആരംഭിക്കുക",
    talkToAi: "AI-യോട് സംസാരിക്കുക",
    watchDemo: "ഡെമോ കാണുക",
    navHome: "ഹോം",
    navChat: "AI അസിസ്റ്റന്റ്",
    navServices: "സർക്കാർ സേവനങ്ങൾ",
    navComplaints: "പരാതികൾ",
    navSchemes: "പദ്ധതികൾ",
    navResources: "വിഭവങ്ങൾ",
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    navProfile: "എന്റെ പ്രൊഫൈൽ",
    heroHeading: "സർക്കാർ സേവനങ്ങൾക്കായി നിങ്ങളുടെ ബുദ്ധിമാനായ AI സഹചാരി",
    heroSubheading: "സർക്കാർ സേവനങ്ങൾ ആക്‌സസ് ചെയ്യുക, പൗരപ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക, രേഖകൾ പരിശോധിക്കുക, പദ്ധതികൾ കണ്ടെത്തുക, ഒന്നിലധികം ഇന്ത്യൻ ഭാഷകളിൽ ഉടനടി AI സഹായം നേടുക.",
    securePortal: "സുരക്ഷിത സർക്കാർ പോർട്ടൽ",
    verifiedBadge: "ഇന്ത്യൻ സർക്കാർ അംഗീകരിച്ചു",
    login: "ലോഗിൻ ചെയ്യുക",
    signup: "സൈൻ അപ്പ് ചെയ്യുക",
    logout: "ലോഗ് ഔട്ട്",
    welcomeBack: "സ്മാർട്ട് ഭാരത് AI-ലേക്ക് സ്വാഗതം",
    chooseRole: "എങ്ങനെ തുടരണമെന്ന് തിരഞ്ഞെടുക്കുക",
    guestMode: "അതിഥിയായി തുടരുക",
    verifyDoc: "രേഖകൾ പരിശോധിക്കുക",
    summarizePdf: "പോളിസി പിഡിഎഫ് സംഗ്രഹം",
    reportIssue: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    searchPlaceholder: "ഇന്ത്യൻ സർക്കാർ സേവനങ്ങളെക്കുറിച്ച് എന്നോട് എന്തും ചോദിക്കാം...",
    aadhaarBadge: "ഡിജിലോക്കർ പരിശോധിച്ചു"
  },
  pa: {
    appTitle: "ਸਮਾਰਟ ਭਾਰਤ AI",
    appSubtitle: "ਭਾਰਤ ਦਾ ਬੁੱਧੀਮਾਨ ਡਿਜੀਟਲ ਨਾਗਰਿਕ ਸਾਥੀ",
    oneNation: "ਇੱਕ ਰਾਸ਼ਟਰ। ਇੱਕ AI ਸਾਥੀ।",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    talkToAi: "AI ਨਾਲ ਗੱਲ ਕਰੋ",
    watchDemo: "ਡੈਮੋ ਦੇਖੋ",
    navHome: "ਮੁੱਖ ਪੰਨਾ",
    navChat: "AI ਸਹਾਇਕ",
    navServices: "ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ",
    navComplaints: "ਸ਼ਿਕਾਇਤਾਂ",
    navSchemes: "ਯੋਜਨਾਵਾਂ",
    navResources: "ਸਰੋਤ",
    navDashboard: "ਡੈਸ਼ਬੋਰਡ",
    navProfile: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
    heroHeading: "ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ ਲਈ ਤੁਹਾਡਾ ਬੁੱਧੀਮਾਨ AI ਸਾਥੀ",
    heroSubheading: "ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚੋ, ਨਾਗਰਿਕ ਮੁੱਦਿਆਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ, ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ, ਯੋਜਨਾਵਾਂ ਲੱਭੋ ਅਤੇ ਕਈ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਤੁਰੰਤ AI ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਕਰੋ।",
    securePortal: "ਸੁਰੱਖਿਅਤ ਸਰਕਾਰੀ ਪੋਰਟਲ",
    verifiedBadge: "ਭਾਰਤ ਸਰਕਾਰ ਦੁਆਰਾ ਪ੍ਰਵਾਨਿਤ",
    login: "ਲੌਗ ਇਨ",
    signup: "ਸਾਈਨ ਅਪ",
    logout: "ਲੌਗ ਆਉਟ",
    welcomeBack: "ਸਮਾਰਟ ਭਾਰਤ AI ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    chooseRole: "ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਕਿਵੇਂ ਜਾਰੀ ਰੱਖਣਾ ਚਾਹੁੰਦੇ ਹੋ",
    guestMode: "ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ",
    verifyDoc: "ਦਸਤਾਵੇਜ਼ ਦੀ ਪੁਸ਼ਟੀ",
    summarizePdf: "ਨੀਤੀ ਪੀਡੀਐਫ ਸਾਰਾਂਸ਼",
    reportIssue: "ਮੁੱਦੇ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
    searchPlaceholder: "ਭਾਰਤੀ ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ...",
    aadhaarBadge: "ਡੀਜੀਲੌਕਰ ਪ੍ਰਮਾਣਿਤ"
  },
  ur: {
    appTitle: "اسمارٹ بھارت AI",
    appSubtitle: "ہندوستان کا ذہین ڈیجیٹل شہری ساتھی",
    oneNation: "ایک قوم۔ ایک AI ساتھی۔",
    getStarted: "شروع کریں",
    talkToAi: "AI سے بات کریں",
    watchDemo: "ڈیمو دیکھیں",
    navHome: "ہوم",
    navChat: "AI معاون",
    navServices: "سرکاری خدمات",
    navComplaints: "شہری شکایتیں",
    navSchemes: "اسکیمیں",
    navResources: "وسائل",
    navDashboard: "ڈیش بورڈ",
    navProfile: "میری پروفائل",
    heroHeading: "سرکاری خدمات کے لیے آپ کا ذہین AI ساتھی",
    heroSubheading: "سرکاری خدمات تک رسائی حاصل کریں، شہری مسائل کی اطلاع دیں، دستاویزات کی تصدیق کریں، اسکیمیں دریافت کریں، اور متعدد ہندوستانی زبانوں میں فوری طور پر AI مدد حاصل کریں۔",
    securePortal: "محفوظ سرکاری پورٹل",
    verifiedBadge: "حکومت ہند سے منظور شدہ",
    login: "لاگ ان کریں",
    signup: "سائن اپ کریں",
    logout: "لاگ آؤٹ",
    welcomeBack: "اسمارٹ بھارت AI میں آپ کا خیرمقدم ہے",
    chooseRole: "منتخب کریں کہ آپ کس طرح جاری رکھنا چاہتے ہیں",
    guestMode: "بطور مہمان جاری رکھیں",
    verifyDoc: "دستاویزات کی تصدیق",
    summarizePdf: "پالیسی پی ڈی ایف خلاصہ",
    reportIssue: "مسئلے کی اطلاع دیں",
    searchPlaceholder: "بھارتی سرکاری خدمات کے بارے میں مجھ سے کچھ بھی پوچھیں...",
    aadhaarBadge: "ڈیجی لاکر تصدیق شدہ"
  },
  bn: {
    appTitle: "স্মার্ট ভারত AI",
    appSubtitle: "ভারতের বুদ্ধিমান ডিজিটাল নাগরিক সহযোগী",
    oneNation: "এক দেশ। এক AI সহযোগী।",
    getStarted: "শুরু করুন",
    talkToAi: "AI এর সাথে কথা বলুন",
    watchDemo: "ডেমো দেখুন",
    navHome: "হোম",
    navChat: "AI সহকারী",
    navServices: "সরকারি পরিষেবা",
    navComplaints: "নাগরিক অভিযোগ",
    navSchemes: "পরিকল্পনা সমূহ",
    navResources: "সম্পদ সমূহ",
    navDashboard: "ড্যাশবোর্ড",
    navProfile: "আমার প্রোফাইল",
    heroHeading: "সরকারি পরিষেবার জন্য আপনার বুদ্ধিমান AI সহযোগী",
    heroSubheading: "সরকারি পরিষেবা অ্যাক্সেস করুন, নাগরিক সমস্যার রিপোর্ট করুন, নথিপত্র যাচাই করুন, সরকারি প্রকল্প আবিষ্কার করুন এবং একাধিক ভারতীয় ভাষায় তাত্ক্ষণিক AI সহায়তা পান।",
    securePortal: "নিরাপদ সরকারি পোর্টাল",
    verifiedBadge: "ভারত সরকার অনুমোদিত",
    login: "লগ ইন",
    signup: "সাইন আপ",
    logout: "লগ আউট",
    welcomeBack: "স্মার্ট ভারত AI তে আপনাকে স্বাগত জানাই",
    chooseRole: "আপনি কীভাবে এগিয়ে যেতে চান তা চয়ন করুন",
    guestMode: "অতিথি হিসাবে এগিয়ে যান",
    verifyDoc: "নথিপত্র যাচাই করুন",
    summarizePdf: "নীতি পিডিএফ সারসংক্ষেপ",
    reportIssue: "সমস্যার রিপোর্ট করুন",
    searchPlaceholder: "ভারতীয় সরকারি পরিষেবা সম্পর্কে আমাকে যেকোনো প্রশ্ন করুন...",
    aadhaarBadge: "ডিজিলকার যাচাইকৃত"
  }
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>("en");

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
